server.port=8080

management.endpoints.web.exposure.include=health,info

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:mem:learning

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.application.name=learning-app

app.name=Learning Application
app.greeting=Welcome

