server.port=8080

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ACTUATOR

management.server.port=8081

management.info.env.enabled=true

logging.level.root=INFO
logging.level.com.learning.boot=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d %-5level [%X{requestId}] %logger - %msg%n

spring.cache.type=simple

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:mem:learning

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://idp.example.com
spring.security.oauth2.resourceserver.jwt.audiences=https://learning-api.example.com
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://idp.example.com/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:my-public-key.pub

spring.application.name=learning-app

app.name=Learning Application
app.greeting=Welcome


info.app.name=learing-api
info.app.version=1.0.0
info.app.description=Spring Boot learning application


